# Generated by Django 5.1.6 on 2025-03-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_trackinglink_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='pdf_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='pdf_sent',
            field=models.BooleanField(default=False),
        ),
    ]
