# Generated by Django 5.1.6 on 2025-03-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_newsletter_pdf_generated_newsletter_pdf_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='status',
            field=models.CharField(default='Draft', max_length=50),
        ),
    ]
