# Generated by Django 5.1.6 on 2025-04-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_newsletter_subscriber_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='schedule_delete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
